/**
 * Tercer lote editorial solicitado el 2026-08-02.
 *
 * Criterios:
 * - 40 personas reales, sin instituciones mal clasificadas ni fichas previas;
 * - 40 ideas diferenciadas de las páginas ya producidas;
 * - 50 preguntas madre gate 5/5 todavía inéditas;
 * - cinco preguntas por cada categoría editorial;
 * - cobertura de los 16 períodos: tres por período y cuatro en C91 y TRANS;
 * - personas con identidad documental suficientemente verificable para portada.
 */
import type { CampaignEntity } from "./campaign-2026-07-25-manifest";

const person = (label: string, key: string): CampaignEntity => ({
  type: "person",
  key: `person:${key}`,
  label,
  intent: `${label}, trayectoria y papel en la historia de Colombia`,
});

const concept = (label: string, key: string): CampaignEntity => ({
  type: "concept",
  key: `concept:${key}`,
  label,
  intent: `${label} como concepto y proceso en la historia de Colombia`,
});

export const CAMPAIGN_ENTITIES: CampaignEntity[] = [
  // Personas — actores políticos, sociales e intelectuales de distintas épocas.
  person("Jorge Isaacs", "jorge-isaacs"),
  person("Don Berna", "don-berna"),
  person("Marco Palacios", "marco-palacios"),
  person("Germán Colmenares", "german-colmenares"),
  person("Lázaro Cárdenas", "lazaro-cardenas"),
  person("Pedro Claver", "pedro-claver"),
  person("Salomón Kalmanovitz", "salomon-kalmanovitz"),
  person("Jaime Arocha", "jaime-arocha"),
  person("Gloria Cuartas", "gloria-cuartas"),
  person("Bartolomé de las Casas", "bartolome-de-las-casas"),
  person("Carlos III de España", "carlos-iii-de-espana"),
  person("Luis Carlos Restrepo", "luis-carlos-restrepo"),
  person("Carlos Cortés Vargas", "cortes-vargas"),
  person("Mauricio Archila", "mauricio-archila"),
  person("Fidel Castro", "fidel-castro"),
  person("Paul Rivet", "paul-rivet"),
  person("Francisco Antonio Zea", "francisco-antonio-zea"),
  person("Jorge Briceño", "jorge-briceno"),
  person("José Vicente Concha", "jose-vicente-concha"),
  person("Doris Salcedo", "doris-salcedo"),
  person("Pedro de Heredia", "pedro-de-heredia"),
  person("Roger Casement", "roger-casement"),
  person("Sergio Jaramillo", "sergio-jaramillo"),
  person("George W. Bush", "george-w-bush"),
  person("Carlos Gaviria", "carlos-gaviria"),
  person("Carlos Lehder", "carlos-lehder"),
  person("Rudolf Hommes", "rudolf-hommes"),
  person("Jaime Garzón", "jaime-garzon"),
  person("Jorge Tadeo Lozano", "jorge-tadeo-lozano"),
  person("Estanislao Zuleta", "estanislao-zuleta"),
  person("Medófilo Medina", "medofilo-medina"),
  person("Ezequiel Rojas", "ezequiel-rojas"),
  person("Benkos Biohó", "benkos-bioho"),
  person("Álvaro Fayad", "alvaro-fayad"),
  person("Guillermo Valencia", "guillermo-valencia"),
  person("Alberto Ruiz Novoa", "alberto-ruiz-novoa"),
  person("Peter Wade", "peter-wade"),
  person("Alonso Salazar", "alonso-salazar"),
  person("Vera Grabe", "vera-grabe"),
  person("Manuela Beltrán", "manuela-beltran"),

  // Ideas — instituciones, procesos y categorías con respaldo transversal.
  concept("ANUC", "anuc"),
  concept("Bogotazo", "bogotazo"),
  concept("Pacto de Chicoral", "pacto-de-chicoral"),
  concept("Latifundio", "latifundio"),
  concept("Reparación integral", "reparacion-integral"),
  concept("Acumulación por desposesión", "acumulacion-por-desposesion"),
  concept("Regeneración", "regeneracion"),
  concept("Gamonalismo", "gamonalismo"),
  concept("Doctrina Monroe", "doctrina-monroe"),
  concept("Colonización dirigida", "colonizacion-dirigida"),
  concept("Zona de despeje", "zona-de-despeje"),
  concept("Exclusión política", "exclusion-politica"),
  concept("Sufragio femenino", "sufragio-femenino"),
  concept("Frontera porosa", "frontera-porosa"),
  concept("Pacto de élites", "pacto-de-elites"),
  concept("Higienismo", "higienismo"),
  concept("Colonización armada", "colonizacion-armada"),
  concept("Hegemonía conservadora", "hegemonia-conservadora"),
  concept("Contrabando", "contrabando"),
  concept("Élites regionales", "elites-regionales"),
  concept("Reclutamiento forzado", "reclutamiento-forzado"),
  concept("Identidad nacional", "identidad-nacional"),
  concept("Posconflicto", "posconflicto"),
  concept("Democracia restringida", "democracia-restringida"),
  concept("Concentración de la tierra", "concentracion-de-la-tierra"),
  concept("Bandas criminales", "bandas-criminales"),
  concept("Privatización de la seguridad", "privatizacion-de-la-seguridad"),
  concept("Tecnocracia", "tecnocracia"),
  concept("Manumisión", "manumision"),
  concept("Sicariato", "sicariato"),
  concept("Foquismo", "foquismo"),
  concept("Secularización", "secularizacion"),
  concept("Bloque de constitucionalidad", "bloque-de-constitucionalidad"),
  concept("Estado paralelo", "estado-paralelo"),
  concept("Economía de guerra", "economia-de-guerra"),
  concept("Plebiscito", "plebiscito"),
  concept("Revolución en Marcha", "revolucion-en-marcha"),
  concept("Guerra Fría", "guerra-fria"),
  concept("Misión Kemmerer", "mision-kemmerer"),
  concept("Indigenismo", "indigenismo"),
];

/**
 * Preguntas madre gate 5/5. Cuotas:
 * - cinco por categoría: CON, CUL, ECO, HIS, INS, MOV, POL, REL, SOC y TER;
 * - tres por período, salvo C91 y TRANS con cuatro cada uno.
 */
export const CAMPAIGN_MASTER_IDS = [
  "cmq6s7jf102qavjhchwidrkli",
  "cmq6s7de302ngvjhc7s9rblte",
  "cmq6s7d4802ncvjhcpe2q0l0t",
  "cmq6s641d021xvjhcxec3zfdw",
  "cmq6s76zp02k1vjhczurxfxyt",
  "cmq6s7gau02oovjhcqj4d5bb2",
  "cmq6s5vgn01wwvjhcg7nbqf8r",
  "cmq6s3f4l00jovjhcuo9jf66f",
  "cmq6s6rfc02cuvjhc43mhziip",
  "cmq6s7qe802tavjhc9s2etsvv",
  "cmq6s7hw802phvjhc0ja58use",
  "cmq6s7bo402mqvjhcf8c9usmg",
  "cmq6s56hc01lovjhca9etobc2",
  "cmq4k1luu084jvjhgm8gguo58",
  "cmq6s2vvx003lvjhcim5ruyxl",
  "cmq6s71x302hsvjhchjy7e77n",
  "cmq6s71gp02hivjhcjcbkxm0e",
  "cmq6s6vxh02ejvjhci9v1a95x",
  "cmq6s41ya00xbvjhct4drr0gb",
  "cmq6s5iu501qwvjhczaoo66h0",
  "cmq6s6gx0028evjhclkjx3mt3",
  "cmq6s47st0105vjhc6815zktg",
  "cmq4k1s2y088kvjhgi9zuvm1f",
  "cmq4k3lx909dhvjhg44xo4niy",
  "cmq4k2ib108o6vjhgtksjkpoq",
  "cmq6s5buk01nqvjhcewbhu690",
  "cmq6s600o01zpvjhcuis99can",
  "cmq4k0034078fvjhg96eppvgl",
  "cmq6s6pel02bzvjhch5f3b33l",
  "cmq4k4m1c09yavjhg1fxvgxkx",
  "cmq4k2yx008z7vjhgkzu7v3n1",
  "cmq4k4qy20a1gvjhgtg20gkqd",
  "cmq4k1yik08c0vjhgq8thiwu2",
  "cmq4jr8j3017jvjhg9jd26hyp",
  "cmq4jwz6005flvjhgiuu18jyt",
  "cmq4k14ig07uxvjhgbu43g10j",
  "cmq4jqk5000nsvjhg5by40lxk",
  "cmq4jvpt804kkvjhgkobjr3m1",
  "cmq4jvcvo04a6vjhgwwxkwadq",
  "cmq4jxdoa05ptvjhgsx6926ru",
  "cmq4jy9ot06bsvjhgz2yaq0ky",
  "cmq4jzovl072rvjhg9drms46i",
  "cmq4k0ydx07rnvjhg0i7o5b57",
  "cmq4k2oz708srvjhgmqcju7i6",
  "cmq6s365g00crvjhcdlzwsf1k",
  "cmq6s3m9t00o2vjhc1fip8sw9",
  "cmq6s4hxv016avjhc2jhawhmb",
  "cmq4k37330953vjhgb2utee4j",
  "cmq6s5m3601shvjhcu2o26rcu",
  "cmq4jx39z05iyvjhgc2tbxnej",
] as const;
